config/routes.rb
GameTracker::Application.routes.draw do
  resources :scores, except: [:index, :show]

  resources :instances, except: :index

  resources :games

  resources :players

  devise_for :users

  get 'stats/player/:player' => 'stats#player'

  root :to => 'players#index'

end

app/models/score.rb
class Score < ActiveRecord::Base
  resourcify

  belongs_to :instance
  belongs_to :player

  attr_accessible :instance_id, :player_id, :score

  def win?
    instance.winning_scores.include? self
  end

  def excluded?
    instance.exclude?
  end

  def result
    if excluded?
      return 'X'
    elsif win?
      return 'W'
    else
      return 'L'
    end
  end

  # Doesn't play nice with mass assign from form
  #validates :instance_id, presence: true
  validates :player_id, presence: true
  validates :score, presence: true
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  load_and_authorize_resource
  # GET /scores/new
  # GET /scores/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @instances = Instance.includes(:game).all
  end

  # POST /scores
  # POST /scores.json
  def create
    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render json: @score, status: :created, location: @score }
      else
        format.html { render action: "new" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scores/1
  # PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end
end

app/views/scores/_form.html.erb
<%= simple_form_for(@score) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :instance, collection: @instances %>
    <%= f.association :player %>
    <%= f.input :score %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Back', @score.instance, class: 'btn' if can? :show, @score.instance %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table class='table'>
  <thead>
    <tr>
        <th><%= Score.human_attribute_name :instance_id%></th>
        <th><%= Score.human_attribute_name :player_id%></th>
        <th><%= Score.human_attribute_name :score%></th>
        <th></th>
    </tr>
  </thead>

  <tbody>
    <%= content_tag_for(:tr, @scores) do |score| %>
        <td><%= score.instance.name %></td>
        <td><%= score.player.name %></td>
        <td><%= score.score %></td>
        <td>
        <div class='btn-group'>
          <%= link_to 'Show', score, class: 'btn' if can? :show, score %>
          <%= link_to 'Edit', edit_score_path(score), class: 'btn btn-warning' if can? :edit, score %>
          <%= link_to 'Destroy', score, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger' if can? :destroy, score %>
        </div>
      </td>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Score', new_score_path, class: 'btn' if can? :new, :score %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path, class: 'btn' if can? :index, :score %>

app/views/scores/show.html.erb
<%= show_for @score do |s| %>
  <%= s.association :instance %>
  <%= s.association :player %>
  <%= s.attribute :score %>
<% end %>

<%= link_to 'Edit', edit_score_path(@score), class: 'btn btn-warning' if can? :edit, @score %>
<%= link_to 'Back', scores_path, class: 'btn' if can? :index, :score %>