config/routes.rb
GameTracker::Application.routes.draw do
  resources :scores, except: [:index, :show]

  resources :instances, except: :index

  resources :games

  resources :players

  devise_for :users

  get 'stats/player/:player' => 'stats#player'

  root :to => 'players#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='navbar navbar-fixed-top'>
    <div class='navbar-inner'>
      <div class='container'>
        <a class='btn btn-navbar' data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'Interactivity Games', root_path, class: 'brand' %>
        <div class="nav-collapse">
          <ul class='nav'>
            <li><%= link_to 'Players', players_path %></li>
            <li><%= link_to 'Games', games_path %></li>
            <li><%= link_to 'New Game Instance', new_instance_path if can? :new, :instance %></li>
          </ul>
          <ul class='nav pull-right'>
            <% if current_user.nil? %>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
            <% else %>
              <li><%= link_to current_user.email, edit_user_registration_path(current_user) %></li>
              <li class='divider-vertical'></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class='container'>
    <% if notice %>
      <div class="alert fade in">
        <a class='close' data-dismiss="alert" href="#">&times;</a>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-error fade in">
        <a class='close' data-dismiss="alert" href="#">&times;</a>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>


</body>
</html>